### ISSUE TITLE
Find a way to automatically get the Streaming API Url

### ISSUE THREAD

**Issue by glacasa** [glacasa/Mastonet#10]
We added a way to define the streaming API Url in the client in PR #3 

It would be better to get this URL automatically

**Comment by kmycode** [comment]
I just post new issue sharp_2068 on Mastodon project.
https://github.com/tootsuite/mastodon/issues/2068

**Comment by glacasa** [comment]
It's not supported for now. 

Until we have a way to get STREAMING_API_BASE_URL from the API, I'm going to hardcode the url for mstdn.jp (and other instances with the same problem if there are)

**Comment by glacasa** [comment]
The instance mstdn.jp no longer uses a different url, so it's not needed anymore.

The API now provides an url for web-socket, that should replace current http streaming, it will replace current streaming, so it should be ok now.
