### ISSUE TITLE
"Revoke a token" method is missing in Mastonet's library

### ISSUE THREAD

**Issue by JeepNL** [glacasa/Mastonet#101]
"Revoke a token" method is missing in Mastonet's library

For implementation see: https://docs.joinmastodon.org/methods/oauth/#revoke

**Comment by glacasa** [comment]
I added the method to the AuthenticationClient, because it needs the same client id and secret as needed for the oauth.

You can test the method on the last Nuget preview, tell me if it works :)

https://www.nuget.org/packages/Mastonet/2.3.0-preview1

**Comment by JeepNL** [comment]
Yup, it works! Thank you! Closing this issue.
