### ISSUE TITLE
Get Markers endpoint needs a timeline query parameter

### ISSUE THREAD

**Issue by distantcam** [glacasa/Mastonet#103]
According to the docs https://docs.joinmastodon.org/methods/markers/#query-parameters

> timeline[]
> Array of String. Specify the timeline(s) for which markers should be fetched. Possible values: home, notifications. **_If not provided, an empty object will be returned._**

The `GetMarkers()` method needs a timeline parameter of either home or notifications.

**Comment by glacasa** [comment]
I have merged the PR and updated the Nuget package. Thanks !
