### ISSUE TITLE
[Request] Use System.Text.Json instead of Newtonsoft.Json / Json.NET & Enable Trimming for Mastonet

### ISSUE THREAD

**Issue by JeepNL** [glacasa/Mastonet#108]
This is not urgent, maybe just something to think about.

When you use Blazor WASM Client Side, the complete WASM project is downloaded by the user's browser, so when I create a Blazor WASM project I've to check which libraries I use to keep the project as small as possible. 

I see Mastonet uses Newtonsoft JSON.NET, and it's a pretty big library (_see screenshot_), and I wondered if using System.Text.Json instead, which is already there, is possible. 

The Mastodon.net library is already pretty small, but maybe it's an idea to support trimming foi Mastonet as well. See for more information about how to enable trimming here (_Prepare .NET libraries for trimming_): https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming

![Screenshot 2023-05-10 174317](https://github.com/glacasa/Mastonet/assets/39458532/c6f185b2-79b2-48d3-8510-c01d244af78b)
(_ordered by size decending, brotli compressed_)

**Comment by glacasa** [comment]
Hi !
I have this in mind since a long time, but I don't really have time to really work on it.

Here is what I have started to do just 2 days ago : 
https://github.com/glacasa/Mastonet/commit/4b93386a4168ec851a220e6b4fcdd5f04229d6a6


There are just 2 custom converters to rewrite : 
https://github.com/glacasa/Mastonet/blob/separate-entities/Mastonet.Entities/Enums/FilterContext.cs
https://github.com/glacasa/Mastonet/blob/separate-entities/Mastonet.Entities/Enums/NotificationType.cs

If you want to make a PR, I will happily merge it ;) 


About the trimming, I don't know how this work at all, I'm going to read this link

**Comment by JeepNL** [comment]
I've never tried to convert JSON.NET code to System.Text.Json but I certainly will take a look at it, this week. I know it's documented somewhere, so maybe I can do it, I'd like to help you out with it! And I've also a ChatGPT Plus (model 4) subscription, so who knows, maybe the A.I. can help me, that would be fun! 😉

About the trimming: like I said, your lib is already small but now with Blazor WASM and the new AOT options maybe it can even be smaller. And it's the 'new & modern thing' for libraries. But there's really no hurry.

**Comment by glacasa** [comment]
Ok, so I just reopened the files to see how hard it would be, and Copilot just wrote the new methods 😄

Everything seems fine and it builds, I just need to test if everything still works

**Comment by JeepNL** [comment]
OH! WOW!! That's soooo cool! 🚀

**Comment by JeepNL** [comment]
You have probably seen this already, but if not (FYI): 

Compare Newtonsoft.Json to System.Text.Json, and migrate to System.Text.Json

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft?pivots=dotnet-7-0

**Comment by eduardobragaxz** [comment]
Just a heads up: some of System.Text.Json throw trimming warnings, even stuff like Serialize/Deserialize. I converted some Newtonsoft.Json to it and was surprised with the warnings. Not sure if source generators would help, haven't tried.

**Comment by JeepNL** [comment]
Reflection-based serializers are causing problems with trimming, as an alternative you can use reflection-free serializers, like source-generated System.Text.Json: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation

Introduction to trim warnings: https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/fixing-warnings

Known trimming incompatibilities: https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/incompatibilities

But the Mastonet library is already very small, so it would be nice if it supports trimming, but not really necessary right now imo.

**Comment by eduardobragaxz** [comment]
Thanks for the links!

**Comment by glacasa** [comment]
This is coming in v3 thanks to PR #112 

Here it is in preview 
https://www.nuget.org/packages/Mastonet/3.0.0-preview1
