### ISSUE TITLE
GetPublicStreaming status.reblog always null

### ISSUE THREAD

**Issue by vantubbe** [glacasa/Mastonet#113]
I've been streaming toots and noticed that this field is always null (for me). If a status received from this stream has been boosted/reblogged, then status.reblog should contain the original toot, correct?

**Comment by glacasa** [comment]
Hello,

This is how it is supposed to work, yes.
I just tried it on the home timeline, and it works fine

I'm not sure, but I don't think Mastodon sends the boosts on public timelines, the posts appears as soon as they reach the instance as normal posts. That would explain why you don't see boosts on this timeline.

**Comment by vantubbe** [comment]
Appreciate the quick feedback! Makes sense, apologies the question was ultimately about Mastodon itself rather than Mastonet. Thanks again.
