### ISSUE TITLE
How i can add the hashtag to my status correctly?

### ISSUE THREAD

**Issue by ketronix-dev** [glacasa/Mastonet#114]
How i can add the hashtag to my status correctly?

This is my code for publishing status:

```c#
using Mastonet;

namespace Mastobot;

class Program
{
    static async Task Main(string[] args)
    {
        var instance = "twiukraine.com";
        var mastodonClient = new MastodonClient(instance, "token");

        await mastodonClient.PublishStatus("status #hashtag", Visibility.Public);
    }
}
```

After running this code, i see normal text instead of hastag.

**Comment by glacasa** [comment]
This is exactly how it is supposed to work.

Just tried it, and the hashtag works fine (https://mastodon.social/@mastonet/111619153182650285)

Not sure what to say… Do the hashtags work using other client apps on your instance ?
