### ISSUE TITLE
Streaming API Not Working in 3.1.0

### ISSUE THREAD

**Issue by Freeesia** [glacasa/Mastonet#117]
After upgrading Mastonet from version 2.3.1 to 3.1.0, I've noticed that events are no longer firing. The APIs I tested include:

* GetPublicStreaming
* GetUserStreaming
* GetDirectMessagesStreaming
There are no exceptions being thrown, so it seems that either the subscription is not starting, or the received WebSocket events are not being notified. The targeted Mastodon version is v4.2.3.

Please let me know if there's anything else I can help with.
Thank you.

**Comment by glacasa** [comment]
It seems streaming messages were not deserialized

I published a fix, can you check if it's better now ?
https://www.nuget.org/packages/Mastonet/3.1.1-beta1

**Comment by Freeesia** [comment]
@glacasa 
I have tested the latest update, version 3.1.1-beta1. I am happy to report that the fix is functioning properly. The streaming API is now operating as expected in version 3.1.1-beta1. Thank you for the prompt resolution of this issue!

**Comment by glacasa** [comment]
Great !
I published it on Nuget as non-beta :)
https://www.nuget.org/packages/Mastonet/3.1.1
