### ISSUE TITLE
Different id type between Status and ArrayOptions

### ISSUE THREAD

**Issue by kmycode** [glacasa/Mastonet#12]
I'm wrong, but id type is different.

In `Status` class, `int Id`.
https://github.com/glacasa/Mastonet/blob/master/Mastonet/Entities/Status.cs

But in `ArrayOptions` class, `string MaxId`.
https://github.com/glacasa/Mastonet/blob/master/Mastonet/ArrayOptions.cs

We need write `MaxId = status.Id.ToString()` because of my miss.
I would like to PR, but it will be destructive change.

I'm sorry...

**Comment by glacasa** [comment]
I've seen it, I'm already working on it. ;)

It's ok for the breaking change, I warned in the README, there's probably gonna be others before a first release

**Comment by kmycode** [comment]
@glacasa Okay, thank you!
