### ISSUE TITLE
JsonSerializationException when calling GetHomeTimeline

### ISSUE THREAD

**Issue by drasticactions** [glacasa/Mastonet#2]
When calling GetHomeTimeline, JSON.net throws an exception when parsing the response.
https://github.com/glacasa/Mastonet/blob/master/Mastonet/MastodonClient.cs#L90
```
Newtonsoft.Json.JsonSerializationException: 'Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Mastonet.Entities.Error' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.

To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.

Path '', line 1, position 1.'
```

The JSON is correct; it's an array of statuses. But because it's an array, it blows up. If you comment out the error handling code, it works.

I'm trying to think of the best way to solve it. Maybe deserialize it as a dynamic object and check for the `error` property, then cast it as error if it is, otherwise deserialize it as `<T>`. Not really sure what's the right way to do it.

**Comment by glacasa** [comment]
I removed the error handling, i think it's better to let an exception be thrown than to block completely the timeline.

I can't look at it further for now because it's Easter and I spend some time with my family ;) 
I'll work on it in 3 or 4 days

**Comment by kmycode** [comment]
How about following code using `if (json[0] == '{')` ?

~~~~
    private T TryDeserialize<T>(string json)
    {
        if (json[0] == '{')
        {
            var error = JsonConvert.DeserializeObject<Error>(json);
            if (!string.IsNullOrEmpty(error.Description))
            {
                throw new ServerErrorException(error);
            }
        }

        ...
~~~~
