### ISSUE TITLE
Status ID 32-bit integer overflow

### ISSUE THREAD

**Issue by watkinsmatthewp** [glacasa/Mastonet#21]
On some of the bigger Mastodon instances, the status IDs currently being assigned have exceeded `int.MaxValue`. It looks like mastodon.social just crossed that threshold in the past few days. Because MastoNet declared status ID to be an int, it causies an exception in the JSON parser when reading the values:

![image](https://user-images.githubusercontent.com/3808901/31546140-1b295a50-aff0-11e7-9d50-95089ca0c7be.png)

It looks like [_all_ Mastodon keys are now 64-bit integers](https://github.com/tootsuite/mastodon/blob/97c02c3389b31b2459ffa157c91b7515ee1f626b/db/migrate/20170918125918_ids_to_bigints.rb), so really every ID in the MastoNet models should probably be converted to `long`s. However, _my_ project is currently only breaking on status ID, so I would like to see _that_ fixed and the NuGet package updated ASAP :)

**Comment by glacasa** [comment]
I have updated all the IDs, and pushed to master :)
I can't test right now, are you able to get the last version and test before I submit the update on Nuget ?

**Comment by watkinsmatthewp** [comment]
Sorry, didn't mean to close. Still awaiting on @Tdortiz's pull request to be merged

**Comment by glacasa** [comment]
I merged the PR, thanks @Tdortiz :)
I will test this further when I come back home tomorrow, and will update Nuget package when I'm sure everything is ok

**Comment by glacasa** [comment]
All the IDs should be ok now.
I build the package and send it to Nuget, it should be available in the next minutes
