### ISSUE TITLE
Does Mastonet handle the internal pagination that Mastodon does?

### ISSUE THREAD

**Issue by Tdortiz** [glacasa/Mastonet#25]
Under a few of the method calls on [Mastodon's Api](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md) they mention how we can't use the returned objects IDs directly because they use internal IDS in some places. Instead, on these requests they pass the internal ids in the `Link Header`.

>Note: max_id and since_id for next and previous pages are provided in the Link header. It is not possible to use the id of the returned objects to construct your own URLs, because the results are sorted by an internal key.

![image](https://user-images.githubusercontent.com/10877317/32335846-2dd3a56e-bfc4-11e7-9b1e-76ee416301d0.png)

Does Mastonet handle these internal ids and expose them to developers?

**Comment by glacasa** [comment]
Yes, for all the methods with pagination, you have a Mastonet method with the same parameters (all are optionals). 
For the followings : 
GetAccountFollowing(long accountId, long? maxId = null, long? sinceId = null, int? limit = null)

Or you can use the ArrayOptions object : 
GetAccountFollowing(long accountId, ArrayOptions options)
(this objects contains the same 3 params : MaxId, SinceId and Limit)

These 2 calls do exactly the same things, you can use whichever you prefer.

**Comment by Tdortiz** [comment]
It seems like it may be better to return a wrapper object for relevant functions that holds:

{
    Pagination  : { 
          Maxid
          Sinceid
          Limit
     }, 
     Entities: [

     ]
}

**Comment by Tdortiz** [comment]
This will have to be cleaned up but heres how to get the max_id and since_id from the `Link` header.

```
protected async Task<string> Get(string route, IEnumerable<KeyValuePair<string, string>> data = null)
{
            string url = "https://" + this.Instance + route;

            if (data != null)
            {
                var querystring = "?" + String.Join("&", data.Select(kvp => kvp.Key + "=" + kvp.Value));
                url += querystring;
            }

            var client = new HttpClient();
            AddHttpHeader(client);
            var response = await client.GetAsync(url);

            IEnumerable<string> values;
            string max_id = string.Empty;
            string since_id = string.Empty;
            if (response.Headers.TryGetValues("Link", out values))
            {
                string linkHeader = values.First();
                // "<https://mastodon.social/api/v1/accounts/1/following?limit=30&max_id=1202169>; rel=\"next\", 
                //  <https://mastodon.social/api/v1/accounts/1/following?limit=30&since_id=1295812>; rel=\"prev\""
                // Check for next page
                if (linkHeader.Contains("rel=\"next\""))
                {
                    string max_id_str = linkHeader.Substring(0, linkHeader.IndexOf("rel=\"next\""));

                    var lower = max_id_str.IndexOf("max_id=");
                    var upper = max_id_str.IndexOf(">");
                    var len = upper-lower;

                    string temp = max_id_str.Substring(lower, len);
                    max_id = temp.Substring(temp.IndexOf("=") + 1);
                }

                // Check for previous page
                if (linkHeader.Contains("rel=\"prev\""))
                {
                    var lower = linkHeader.IndexOf("since_id=");
                    var upper = linkHeader.LastIndexOf(">");
                    var len = upper - lower;

                    string temp = linkHeader.Substring(lower, len);
                    since_id = temp.Substring(temp.IndexOf("=") + 1);
                }
            }

            var content = await response.Content.ReadAsStringAsync();
            content += max_id;
            content += since_id;

            return await response.Content.ReadAsStringAsync();
        }
```

**Comment by glacasa** [comment]
Thanks for the code :)
I probably should find a way to return this without breaking existing code.

Would it make sense if I add an optional out param to the `Get` methods ?

`    public Task<IEnumerable<Status>> GetHomeTimeline(long? maxId = null, long? sinceId = null, int? limit = null)
    public Task<IEnumerable<Status>> GetHomeTimeline(out PaginationData pagination, long? maxId = null, long? sinceId = null, int? limit = null)
    public Task<IEnumerable<Status>> GetHomeTimeline(ArrayOptions options)
    public Task<IEnumerable<Status>> GetHomeTimeline(ArrayOptions options, out PaginationData pagination)`

**Comment by Tdortiz** [comment]
I'm not a **huge** fan of using an `optional out` as it makes sense to me to return a `wrapper object` around a list like the below code. The benefits of this approach are that the returned data is packaged nicely together and in most cases for Mastodon if we're getting a list of items we're going to want the pagination to come alongside that list.

That being said not breaking preexisting code is always nice; there are definitely trade offs here. Perhaps @watkinsmatthewp can give input here as well.

```
public Class ListWrapper {
        List<Item> items { get; set; }
        PaginationData pagination { get; set; }
}
```

**Comment by glacasa** [comment]
I have started working on it, and I think you're right.
It doesn't really make sense to keep the current functions as is, because pagination is a basic feature, it needs to be accessed easily.

Go for the breaking change

**Comment by watkinsmatthewp** [comment]
Also not a huge fan of out parameters. If it were me, I'd create a new method that returns the new paged response class or something to maintain parity with the Mastodon API. But I'd keep the original method around and just mark it as obsolete for a few releases at least so you don't break everyone else right away

**Comment by glacasa** [comment]
I have updated the code.
I would like to publish a pre-release Nuget package, but Nuget (and my VSTS build) seem to be down...

The methods returning `IEnumerable<T>` now returns `MastodonList<T>`
https://github.com/glacasa/Mastonet/blob/master/Mastonet/Entities/MastodonList.cs

Also, I have made a Mastonet.Compat.MastodonClient : same as the old MastodonClient
Just need to change the namespace to keep your app working

**Comment by glacasa** [comment]
Found a better way to do this today : 
`MastodonList<T>` innherits `List<T>`, so it stays mostly compatible with the previous versions (using `IEnumerable<T>`), and contains 2 more properties : `NextPageMaxId` and `PreviousPageSinceId`

I have published a pre-release package on Nuget. If everything is ok after testings, I will release v1.1 and close this issue.
https://www.nuget.org/packages/Mastonet/1.1.0-beta1

**Comment by Tdortiz** [comment]
I see you allow for the max/since ids to default to 0 since they are type `long` but it may be better for the typing to be `long?` which will allow the max/since ids to be null if the ids were not specified.

**Comment by glacasa** [comment]
I assumed the `max/since ids` are supposed to be always defined by Mastodon, is there a case where we only have only one of them / or none ?

**Comment by watkinsmatthewp** [comment]
@glacasa those max/since are optional per the Mastodon API. There are cases where you would want one and not the other. For example:

- I want all elements since a particular ID (ex. notifications since the AJAX poll): I would want to specify a since id but not a max ID since I don't know what the newest ID might be
- The user scrolls down in their notification feed so I want to grab the next oldest "page" of notifications. So I would specify a max id but not a since id since I don't know what the oldest id of the previous page might be.

**Comment by watkinsmatthewp** [comment]
Whoops, sorry-- I misunderstood the question. I thought you were saying the max/since ids would always be populated by the _user_. My bad

**Comment by glacasa** [comment]
I view it this way : 
- Mastodon server always sends the MaxId and SinceId
- user will use either maxid (for next page/older) or sinceId (for previous page, newer), with a limit (or default value) - the 3 are optionals when calling API methods

**Comment by Tdortiz** [comment]
@glacasa Example of when Mastodon server only sends `since_id`

![image](https://user-images.githubusercontent.com/10877317/32610140-d19a089e-c52f-11e7-87cf-144cfb1ce80e.png)

**Comment by watkinsmatthewp** [comment]
@glacasa thanks for updating all those methods to return `MastodonList` objects. But is there any reason the search account methods were never updated? Thanks!

**Comment by watkinsmatthewp** [comment]
ah makes sense. But I'm really surprised they don't support paging through account search results. Thanks!

**Comment by glacasa** [comment]
Mastodon 1.1 released on Nuget :)

**Comment by Tdortiz** [comment]
Just wanted to comment on this and saying that the new pagination has been working beautifully! Thanks!
