### ISSUE TITLE
UpdateCredentials fails with invalid URI exception

### ISSUE THREAD

**Issue by watkinsmatthewp** [glacasa/Mastonet#28]
Whenever we use the `UpdateCredentials` method with an avatar and header image, it fails with a an invalid URI exception. Here is an example test you can run to demonstrate this:

```cs
public class DebugTest
{
    HttpClient _httpClient = new HttpClient();

    [Fact]
    public void Test()
    {
        var registration = new AppRegistration { /* CREDS HERE */};
        var auth = new Auth { /* CREDS HERE */};
        var avatarBase64 = DownloadBase64("http://tweeting.com/wp-content/uploads/2011/11/Doctor-Who-logo.jpg");
        Assert.Equal(15920, avatarBase64.Length);
        var headerBase64 = DownloadBase64("http://www.geekbomb.net/wp-content/uploads/2017/07/The-police-Box-TARDIS-from-Doctor-Who-in-space.jpg");
        Assert.Equal(336848, headerBase64.Length);

        var mastodonClient = new MastodonClient(registration, auth);
        var result = mastodonClient.UpdateCredentials("Just the Doctor", "Trust me", avatarBase64, headerBase64).Synchronously();
        // ^^^ throws System.AggregateException : One or more errors occurred. (Invalid URI: The Uri string is too long.) ^^^
    }

    private string DownloadBase64(string url)
    {
        return Convert.ToBase64String(_httpClient.GetByteArrayAsync(url).Synchronously());
    }
}
```

My guess is that the problem lies in the fact that Mastonet sends the underlying PATCH call as a `FormUrlEncodedContent` since that effectively throws all the data into the URL (yikes!)

Also, I don't see anything in the documentation about the avatar and header image needing to be a base64-encoded string in the first place. I would kind of expect it to be a normal upload like [media uploads](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#media).

**Comment by watkinsmatthewp** [comment]
Awesome! Is this something upcoming soon-ish, or something more on the backburner?

**Comment by glacasa** [comment]
Ok, I just found the problem.

The PATCH request sends the data in the body (The URI related error is misleading, I think it's about the data deserialization), so this point is ok
![image](https://user-images.githubusercontent.com/4581370/32805473-d5e229a0-c989-11e7-9890-b73f0380a80c.png)

The problem was that the base64 encoded file needs to begin with `data:...`

With this code I was able to update the images : 

`var result = await client.UpdateCredentials("Just the Doctor", "Trust me", "data:image/jpg;base64,"+ avatarBase64);`

You can expect an update to Mastonet soon (probably next week, because I have a lot to do this week)

**Comment by glacasa** [comment]
I just fixed this : we don't need to use base64 encoding any more, we can do normal upload, just like you said.

Now we have a MediaDefinition object, containing a Stream and the FileName, it can be used to upload medias for a toot, or for avatar and header in UpdateCredentials.

A pre-release package is available on NuGet 
https://www.nuget.org/packages/Mastonet/1.2.0-beta1

**Comment by watkinsmatthewp** [comment]
Hi @glacasa I pulled the pre-release package from Nuget and it doesn't seem to have the new method signature:

![image](https://user-images.githubusercontent.com/3808901/33330356-aa5acfb4-d42c-11e7-942f-f0a059803f9d.png)

**Comment by glacasa** [comment]
Oh, my bad, I didn't build the correct branch.

Here is a new package with the update and the last PR merged :)
https://www.nuget.org/packages/Mastonet/1.2.0-beta2

**Comment by watkinsmatthewp** [comment]
```txt
System.ArgumentException: The value cannot be null or empty.
Parameter name: name
   at System.Net.Http.MultipartFormDataContent.Add(HttpContent content, String name, String fileName)
   at Mastonet.BaseHttpClient.<PatchMedia>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mastonet.BaseHttpClient.<Patch>d__23`1.MoveNext()
```

**Comment by watkinsmatthewp** [comment]
@glacasa found the bug and submitted a PR for it. Let me know once you can push the preview update to NuGet

**Comment by glacasa** [comment]
Merged and on Nuget : 
https://www.nuget.org/packages/Mastonet/1.2.0-beta3

**Comment by watkinsmatthewp** [comment]
Thanks!

**Comment by glacasa** [comment]
Bug fixed in the last release : 
https://www.nuget.org/packages/Mastonet/1.2.0
