### ISSUE TITLE
Support Direct Messages Streaming

### ISSUE THREAD

**Issue by lyze237** [glacasa/Mastonet#37]
Hello!

There's a [streaming api for direct messages](https://docs.joinmastodon.org/api/streaming/#get-api-v1-streaming-direct) and mastonet doesn't support it currently.

Hope somebody could implement that.

Thanks :)

**Comment by glacasa** [comment]
Hi, thanks for your feedback.

I don't have time to test it now, but the code is pretty simple.
I made a PR #38 with the streaming, if you (or anybody else) can test it and confirm it works fine, I will merge.

**Comment by lyze237** [comment]
I've just created a little test program and debugged through it since it doesn't work.

The api sends a `event: conversation` which isn't handled in [TimelineStreaming](https://github.com/glacasa/Mastonet/blob/streaming/Mastonet/TimelineStreaming.cs#L54)

**Comment by lyze237** [comment]
Thank you for creating this awesome library. Appreciate it.

**Comment by glacasa** [comment]
Thanks for the PR :)
I have published the update on Nuget as a prerelease version : https://www.nuget.org/packages/Mastonet/1.4.2-preview1

I need to update the full library because lots of API endpoints are missing
