### ISSUE TITLE
Mastodon v3.3.0 streaming is broken

### ISSUE THREAD

**Issue by sftblw** [glacasa/Mastonet#73]
# What happens:

exception on user streaming notification.

- happens after: Mastodon v3.3.0

# Caused by:

- tootsuite/mastodon#14524 and more (3) - see [mastodon release note](https://github.com/tootsuite/mastodon/releases/tag/v3.3.0)

Mastodon 3.3.0 introduces multiple streaming subscription in one connection, thus stream kind key "stream" looks like now array.

https://github.com/glacasa/Mastonet/blob/a8afac55f61d3e8938080b7260935dcd44102b53/Mastonet/TimelineWebSocketStreaming.cs#L84

This causes exception on this data:

```text
{"stream":["user"],"event":"notification","payload":"{ (user object is manually removed) }"}
```

exception: `Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path 'stream', line 1, position 11.` so, array part, `"stream": ["user"]`.

**Comment by glacasa** [comment]
Hello, thanks for your message.
I have fixed the streaming issue, it is now on Nuget : https://www.nuget.org/packages/Mastonet/1.8.2

There is more work to support this new Mastodon feature, I have added an issue to track it #76
