### ISSUE TITLE
client doesn't connect to the instance 

### ISSUE THREAD

**Issue by V1rusFalcon** [glacasa/Mastonet#77]
```c#
var httpClient = new HttpClient();
var authclient = new AuthenticationClient(URL, httpClient);
var appRegistration = authclient.CreateApp("Bot", Scope.Read | Scope.Write | Scope.Follow).Result;
```
_I_ error: `HttpRequestException: No connection could be made because the target machine actively refused it. (https:443)`
_II_ error: `SocketException: No connection could be made because the target machine actively refused it.
`

though it works using postman

**Comment by V1rusFalcon** [comment]
i've just tried with https://mastodon.gamedev.place/ and doesn't work either. i'm using mastonet, last version downloaded from nuget

**Comment by glacasa** [comment]
What version of .NET are you using ?
There is a known issue with old version of .NET framework (<4.6), where TLS 1.2 isn't enabled.
Go see [the docs](https://github.com/glacasa/Mastonet/blob/main/DOC.md) (bottom of page)

**Comment by V1rusFalcon** [comment]
.net5

**Comment by glacasa** [comment]
It works here, so I don't know what to say 🤷‍♂️
![image](https://user-images.githubusercontent.com/4581370/121696661-92cd4f80-cacc-11eb-8064-69d2e94a6062.png)

Maybe some network configuration in your app or your computer ?

**Comment by V1rusFalcon** [comment]
thank you, it was the https:// in the url that was causing the error

**Comment by glacasa** [comment]
Thanks for the feedback.
I leave this issue open for now, I will try to update the docs to avoid this error

**Comment by glacasa** [comment]
On next version, the code will check if the instance name starts with https: and removes it.
