### ISSUE TITLE
videos

### ISSUE THREAD

**Issue by V1rusFalcon** [glacasa/Mastonet#78]
how can i attach video to the post? i've tried:
```c#
System.Net.WebRequest request = System.Net.WebRequest.Create(item.URL);
System.Net.WebResponse response = request.GetResponse();
string responseStream;
using (var reader = new StreamReader(response.GetResponseStream()))
{
     responseStream = reader.ReadToEnd();
}
Attachments.Add(Bot.Mastodon.UploadMedia(new MediaDefinition(new MemoryStream(Encoding.UTF8.GetBytes(responseStream), true), "media")).Result);```

**Comment by glacasa** [comment]
Hello 

Sorry I didn't answer earlier - I'm coming back to this project as a lot of devs have started using it

You can see sample code to upload media in the unit tests : https://github.com/glacasa/Mastonet/blob/main/Mastonet.Tests/PostTests.cs
It should work the same with videos
