### ISSUE TITLE
To use max_id or since_id parameter

### ISSUE THREAD

**Issue by kmycode** [glacasa/Mastonet#8]
All of returning `IEnumerable<>` apis are also have `max_id` and `since_id` parameters.

> **Selecting ranges**
> 
> For most GET operations that return arrays, the query parameters max_id and since_id can be used to specify the range of IDs to return. API methods that return collections of items can return a Link header containing URLs for the next and prev pages. See the Link header RFC for more information.

https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#notes

I want to use that parameters on Mastonet.

I tried to write code for PR, but I got lost because of the design...
There are few similar methods. I want to understand owner's design style.

Idea 1:
~~~~
public Task<IEnumerable<Status>> GetHomeTimeline(ArrayOptions options = null)
~~~~
~~~~
await this.client.GetHomeTimeline(new ArrayOptions
{
    MaxId = "123456",
});
~~~~

Idea 2:
~~~~
public Task<IEnumerable<Status>> GetHomeTimeline(string maxId = null, string sinceId = null)
~~~~
~~~~
await this.client.GetHomeTimeline(maxId: "123456");
~~~~

**Comment by drasticactions** [comment]
@kmycode Idea 1 makes the most sense to me, as you may want to only set a `since_id`, and having to call `client.GetHomeTimeline(null, sinceId)` is kinda strange, IMO.

**Comment by kmycode** [comment]
@drasticactions thank you! I made PR with using idea 1.

**Comment by glacasa** [comment]
I personnally prefer the second idea, because we can use the named parameters and write only the ones we want to use.
But we can overload the methods and have both, don't you think ?

**Comment by kmycode** [comment]
@glacasa 
Umm... I personally think idea 1 is easy to read and maintainable, but idea 2 is easy to write and simple.

> But we can overload the methods and have both, don't you think ?
It may be better, I think.

**Comment by glacasa** [comment]
Ok, I'll merge the PR and add the overloads today

**Comment by kmycode** [comment]
I appreciate your help!
