### ISSUE TITLE
MastodontClient usage example in documentation suggests a non-existent constructor

### ISSUE THREAD

**Issue by ChayoteJarocho** [glacasa/Mastonet#81]
Found a problem in the last lines in the DOC.md file: https://github.com/glacasa/Mastonet/blame/main/DOC.md#L74-L79

The example is suggesting to use a `MastodonClient` constructor that takes an `AppRegistration` object and an `Auth` object as the two first arguments, but there's no such constructor: https://github.com/glacasa/Mastonet/blob/de490d6f4b2e7e921764948b867548c02434b186/Mastonet/MastodonClient.cs#L16-L28

I would offer a PR to fix it but I'm not sure what the correct usage would be.

**Comment by ChayoteJarocho** [comment]
> _I would offer a PR to fix it but I'm not sure what the correct usage would be._

I _think_ this is what was meant:

```cs
    var mastodonClient = new MastodonClient(appRegistration.Instance, auth.AccessToken, httpClient);
```

Is this correct?

**Comment by glacasa** [comment]
Hello ! :)

I've been working on a major update, with a few API change.
The `MastodonClient` ctor now is more simple to use (we only need the instance name and access token, as you have noted)

I updated the doc. Thanks

**Comment by ChayoteJarocho** [comment]
Great, thanks!
