### ISSUE TITLE
Status ID now string instead of long?

### ISSUE THREAD

**Issue by jacobussystems** [glacasa/Mastonet#82]
Hi,
Many thanks for this package!
I'm just wondering why the Status Id has now changed to a string, rather than the previous long?
Thanks,
Jim

**Comment by glacasa** [comment]
Hi Jim !

I've updated the lib to be as close as the official API documentation as possible : 
https://docs.joinmastodon.org/entities/Status/#id

Ids are defined as strings - "cast from an integer but not guaranteed to be a number"
So long are workings, without any guarantee it won't break any day.

Some other developers may create other servers with Mastodon-compatible APIs, maybe one of them will use string ids - so I think it's better to be as compatible as possible with every case

**Comment by jacobussystems** [comment]
Many thanks Guillaume.
I thought I should check with you, as it has some implications for my code, but all understood (and agreed)!
I don't understand that text: "_cast from an integer but not guaranteed to be a number_" - maybe they simply meant that all previous server implementations used an integer?
