### ISSUE TITLE
Add missing APIs for tags

### ISSUE THREAD

**Issue by bitbonk** [glacasa/Mastonet#92]
Mastodon has some APIs for tags that are still missing in `IMastodonClient`:
- view information about a single tag: https://docs.joinmastodon.org/methods/tags/#get
- follow a tag: https://docs.joinmastodon.org/methods/tags/#follow
- unfollow a tag: https://docs.joinmastodon.org/methods/tags/#unfollow
- view followed tags: https://docs.joinmastodon.org/methods/followed_tags/#get

It would be cool, if they would be added.

**Comment by glacasa** [comment]
It's done, you can get the last nuget package (2.0.3), and you will have the new  methods :

    Task<Tag> GetTagInfo(string tag);
    Task<Tag> FollowTag(string tag);
    Task<Tag> UnfollowTag(string tag);
    Task<MastodonList<Tag>> ViewFollowedTags(ArrayOptions? options = null);
