### ISSUE TITLE
Expose instance configuration info

### ISSUE THREAD

**Issue by 13xforever** [glacasa/Mastonet#93]
[As per docs](https://docs.joinmastodon.org/methods/instance/#v2), [`instance`](https://docs.joinmastodon.org/entities/Instance/) `configuration` object is included for mastadon v4, and includes many vital settings needed for proper client utilization (such as status length limit and supported media types).

**Comment by glacasa** [comment]
I have added the V2 version of the Api

The method `GetInstance()` is now marked Obsolete, a new method `GetInstaceV2()`

It's live on the nuget package version 2.1.0
