### ISSUE TITLE
[Feature Request] Implement EditStatus() method

### ISSUE THREAD

**Issue by 13xforever** [glacasa/Mastonet#95]
[As per docs](https://docs.joinmastodon.org/methods/statuses/#edit) it is now possible to edit existing status messages. As far as I can tell, it's the same as `PublishStatus()`, but requires existing status id.

**Comment by glacasa** [comment]
The method EditStatus is now available in Mastonet 2.2.0 on Nuget

**Comment by 13xforever** [comment]
I have to say, I did not expect such prompt response, and it is highly appreciated 🙏
