### ISSUE TITLE
[QUESTION] Is it possible to update a registered app?

### ISSUE THREAD

**Issue by JeepNL** [glacasa/Mastonet#98]
When I register a new app on a selected Mastodon instance with (for example)

```
authClient = new AuthenticationClient("mastodon.social");
appRegistration = await authClient.CreateApp(
    "Example App", // Name
    Scope.Read | Scope.Write | Scope.Follow,  // Scopes
    "https://example.com",  // Website
    "https://example.com/return"  // Redirect Uri
);
```

is it possible to update that app on the Mastodon instance? When I would like to change the App's name or add/change a redirect uri?

**Comment by glacasa** [comment]
The Mastodon API only allows to create a new app. https://docs.joinmastodon.org/methods/apps/

You can always create a new app, and use it for all future oauth connections, old tokens will stay functionnals

**Comment by JeepNL** [comment]
Ah, okay. Thank you for your answer!
